"""verificacion de email, revocacion por sesion, rate limiting en BD

Revision ID: 2962bb94461d
Revises: 8fab429303b5
Create Date: 2026-09-21 10:22:30.497595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2962bb94461d'
down_revision: Union[str, Sequence[str], None] = '8fab429303b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_attempts_created_at'), 'rate_limit_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_rate_limit_attempts_id'), 'rate_limit_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_attempts_key'), 'rate_limit_attempts', ['key'], unique=False)
    op.create_index(op.f('ix_rate_limit_attempts_scope'), 'rate_limit_attempts', ['scope'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    # ### end Alembic commands ###

    # Backfill: usuarios ya existentes quedan como no verificados (NULL rompería
    # la respuesta de la API, que espera is_verified como bool no-nulo)
    op.execute("UPDATE users SET is_verified = 0 WHERE is_verified IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_revoked_tokens_expires_at'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_rate_limit_attempts_scope'), table_name='rate_limit_attempts')
    op.drop_index(op.f('ix_rate_limit_attempts_key'), table_name='rate_limit_attempts')
    op.drop_index(op.f('ix_rate_limit_attempts_id'), table_name='rate_limit_attempts')
    op.drop_index(op.f('ix_rate_limit_attempts_created_at'), table_name='rate_limit_attempts')
    op.drop_table('rate_limit_attempts')
    # ### end Alembic commands ###
