"""agregar tokens_valid_after a users para revocacion de sesiones

Revision ID: 8fab429303b5
Revises: 3db46dee5e1e
Create Date: 2026-09-21 10:04:20.698975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fab429303b5'
down_revision: Union[str, Sequence[str], None] = '3db46dee5e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens_valid_after', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens_valid_after')
    # ### end Alembic commands ###
